title: Francisco García Atienza
description: Computational Mathematician | SciML & Data Science
theme: jekyll-theme-architect
logo: /assets/profile.jpg
email: fragarat@gmail.com
linkedin_username: franciscoatienza
